#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=installing_transformers_pip
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:45:00
#SBATCH --mem=32000M
#SBATCH --output=installing_transformers_pip_%A.out
#SBATCH --error=installing_transformers_pip_%A.err

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate dl2023

pip install transformers

pip install lightning